"""add permissions and role permissions

Revision ID: 1504f43f114b
Revises: e039a37b664a
Create Date: 2026-04-25 14:18:28.016639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1504f43f114b'
down_revision: Union[str, Sequence[str], None] = 'e039a37b664a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_companies_name_lower'), table_name='companies')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_companies_name_lower'), 'companies', [sa.literal_column('lower(name::text)')], unique=True)
    # ### end Alembic commands ###
