"""add company_id to approval instance

Revision ID: 15bf2562382c
Revises: 4654a24ec711
Create Date: 2026-04-16 11:43:23.315557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15bf2562382c'
down_revision: Union[str, Sequence[str], None] = '4654a24ec711'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approval_instances', sa.Column('company_id', sa.UUID(), nullable=False))
    op.create_index('idx_company_id', 'approval_instances', ['company_id'], unique=False)
    op.create_index('idx_entity_id', 'approval_instances', ['entity_id'], unique=False)
    op.create_index('idx_workflow_id', 'approval_instances', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_workflow_id', table_name='approval_instances')
    op.drop_index('idx_entity_id', table_name='approval_instances')
    op.drop_index('idx_company_id', table_name='approval_instances')
    op.drop_column('approval_instances', 'company_id')
    # ### end Alembic commands ###
