"""add user onboarding tokens

Revision ID: 1fb5b1be01f7
Revises: 9915eb5e6e3c
Create Date: 2026-05-08 20:18:01.351574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fb5b1be01f7'
down_revision: Union[str, Sequence[str], None] = '9915eb5e6e3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_onboarding_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_onboarding_tokens_company_id'), 'user_onboarding_tokens', ['company_id'], unique=False)
    op.create_index('ix_user_onboarding_tokens_company_user', 'user_onboarding_tokens', ['company_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_user_onboarding_tokens_token_hash'), 'user_onboarding_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_user_onboarding_tokens_user_id'), 'user_onboarding_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_onboarding_tokens_user_id'), table_name='user_onboarding_tokens')
    op.drop_index(op.f('ix_user_onboarding_tokens_token_hash'), table_name='user_onboarding_tokens')
    op.drop_index('ix_user_onboarding_tokens_company_user', table_name='user_onboarding_tokens')
    op.drop_index(op.f('ix_user_onboarding_tokens_company_id'), table_name='user_onboarding_tokens')
    op.drop_table('user_onboarding_tokens')
    # ### end Alembic commands ###
