"""Add contact_person to Supplier

Revision ID: 24bc49f96c1f
Revises: ca3517974148
Create Date: 2026-03-12 15:53:34.070837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24bc49f96c1f'
down_revision: Union[str, Sequence[str], None] = 'ca3517974148'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('contact_person', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'contact_person')
    # ### end Alembic commands ###
