"""fix workflow and workflow level improvements

Revision ID: 35bfc5ed193a
Revises: 1e1258345b26
Create Date: 2026-03-21 22:10:29.306898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35bfc5ed193a'
down_revision: Union[str, Sequence[str], None] = '1e1258345b26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_workflow_name_per_company', 'approval_workflows', ['company_id', 'name'])
    op.add_column('workflow_levels', sa.Column('name', sa.String(), nullable=True))
    op.drop_constraint(op.f('uq_workflow_level-level_order'), 'workflow_levels', type_='unique')
    op.create_index('ix_workflow_levels_workflow_id', 'workflow_levels', ['workflow_id'], unique=False)
    op.create_unique_constraint('uq_workflow_level_level_order', 'workflow_levels', ['workflow_id', 'level_order'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_workflow_level_level_order', 'workflow_levels', type_='unique')
    op.drop_index('ix_workflow_levels_workflow_id', table_name='workflow_levels')
    op.create_unique_constraint(op.f('uq_workflow_level-level_order'), 'workflow_levels', ['workflow_id', 'level_order'], postgresql_nulls_not_distinct=False)
    op.drop_column('workflow_levels', 'name')
    op.drop_constraint('uq_workflow_name_per_company', 'approval_workflows', type_='unique')
    # ### end Alembic commands ###
