"""fix invoice relationships

Revision ID: 4654a24ec711
Revises: b78b014e2acc
Create Date: 2026-04-11 20:09:24.333918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4654a24ec711'
down_revision: Union[str, Sequence[str], None] = 'b78b014e2acc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('purchase_order_items_department_id_fkey'), 'purchase_order_items', type_='foreignkey')
    op.drop_column('purchase_order_items', 'department_id')
    op.add_column('purchase_orders', sa.Column('department_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'purchase_orders', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.drop_column('purchase_orders', 'department_id')
    op.add_column('purchase_order_items', sa.Column('department_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('purchase_order_items_department_id_fkey'), 'purchase_order_items', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###
