"""add created at and updated at in workflow level roles

Revision ID: 628b801ccbd0
Revises: d28af84e13aa
Create Date: 2026-03-02 14:06:13.130480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '628b801ccbd0'
down_revision: Union[str, Sequence[str], None] = 'd28af84e13aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_level_roles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('workflow_level_roles', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_level_roles', 'updated_at')
    op.drop_column('workflow_level_roles', 'created_at')
    # ### end Alembic commands ###
