"""add currency to company

Revision ID: 64551be44d22
Revises: 5bad8321f7fa
Create Date: 2026-05-01 19:35:49.298141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64551be44d22'
down_revision: Union[str, Sequence[str], None] = '5bad8321f7fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "companies",
    sa.Column(
        "currency",
        sa.String(),
        nullable=False,
        server_default="KES",
    ),
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'currency')
    # ### end Alembic commands ###
