"""add phone number and password to user model

Revision ID: 6eb08ded0c66
Revises: dc84444f46ba
Create Date: 2026-02-26 16:00:00.370413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eb08ded0c66'
down_revision: Union[str, Sequence[str], None] = 'dc84444f46ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['phone_number'])
    op.drop_constraint(op.f('uq_workflow_levels_level_order'), 'workflow_levels', type_='unique')
    op.create_unique_constraint('uq_workflow_level-level_order', 'workflow_levels', ['workflow_id', 'level_order'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_workflow_level-level_order', 'workflow_levels', type_='unique')
    op.create_unique_constraint(op.f('uq_workflow_levels_level_order'), 'workflow_levels', ['workflow_id', 'level_order'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
