"""add user onboarding lifecycle fields

Revision ID: 83b98ebc4aa3
Revises: 1fb5b1be01f7
Create Date: 2026-05-10 13:21:59.386018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83b98ebc4aa3'
down_revision: Union[str, Sequence[str], None] = '1fb5b1be01f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "users",
        sa.Column(
            "has_completed_onboarding",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )

    op.add_column(
        "users",
        sa.Column(
            "onboarded_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )

    # Remove DB-level default after backfill
    op.alter_column(
        "users",
        "has_completed_onboarding",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarded_at')
    op.drop_column('users', 'has_completed_onboarding')
    # ### end Alembic commands ###
