"""add department to purchase order

Revision ID: b78b014e2acc
Revises: edf4f55b732e
Create Date: 2026-04-11 10:31:33.715959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b78b014e2acc'
down_revision: Union[str, Sequence[str], None] = 'edf4f55b732e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order_items', sa.Column('department_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'purchase_order_items', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase_order_items', type_='foreignkey')
    op.drop_column('purchase_order_items', 'department_id')
    # ### end Alembic commands ###
