"""add exchange rates and base currency fields

Revision ID: b94698714f93
Revises: 345d367124d8
Create Date: 2026-05-14 16:05:51.040199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b94698714f93'
down_revision: Union[str, Sequence[str], None] = '345d367124d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        CREATE TABLE IF NOT EXISTS exchange_rates (
            id UUID PRIMARY KEY,
            company_id UUID NOT NULL REFERENCES companies(id),
            from_currency VARCHAR(3) NOT NULL,
            to_currency VARCHAR(3) NOT NULL,
            rate NUMERIC(18, 6) NOT NULL,
            source VARCHAR NOT NULL,
            effective_date DATE NOT NULL,
            created_by UUID REFERENCES users(id),
            created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
            CONSTRAINT uq_exchange_rate_company_currency_date
                UNIQUE (company_id, from_currency, to_currency, effective_date)
        )
    """)

    op.execute("""
        CREATE INDEX IF NOT EXISTS ix_exchange_rates_company_id
        ON exchange_rates (company_id)
    """)

    op.execute("""
        CREATE INDEX IF NOT EXISTS ix_exchange_rates_created_by
        ON exchange_rates (created_by)
    """)

    op.execute("""
        CREATE INDEX IF NOT EXISTS ix_exchange_rates_company_pair_date
        ON exchange_rates (company_id, from_currency, to_currency, effective_date)
    """)
    op.add_column('invoices', sa.Column('currency', sa.String(length=3), server_default='KES', nullable=False))
    op.add_column('invoices', sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), nullable=True))
    op.add_column('invoices', sa.Column('base_currency', sa.String(length=3), nullable=True))
    op.add_column('invoices', sa.Column('base_amount', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('exchange_rate_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('payments', sa.Column('currency', sa.String(length=3), server_default='KES', nullable=False))
    op.add_column('payments', sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), nullable=True))
    op.add_column('payments', sa.Column('base_currency', sa.String(length=3), nullable=True))
    op.add_column('payments', sa.Column('base_amount', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('payments', sa.Column('exchange_rate_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('purchase_orders', sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), nullable=True))
    op.add_column('purchase_orders', sa.Column('base_currency', sa.String(length=3), nullable=True))
    op.add_column('purchase_orders', sa.Column('base_amount', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('purchase_orders', sa.Column('exchange_rate_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('purchase_requisitions', sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), nullable=True))
    op.add_column('purchase_requisitions', sa.Column('base_currency', sa.String(length=3), nullable=True))
    op.add_column('purchase_requisitions', sa.Column('base_amount', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('purchase_requisitions', sa.Column('exchange_rate_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_requisitions', 'exchange_rate_date')
    op.drop_column('purchase_requisitions', 'base_amount')
    op.drop_column('purchase_requisitions', 'base_currency')
    op.drop_column('purchase_requisitions', 'exchange_rate')
    op.drop_column('purchase_orders', 'exchange_rate_date')
    op.drop_column('purchase_orders', 'base_amount')
    op.drop_column('purchase_orders', 'base_currency')
    op.drop_column('purchase_orders', 'exchange_rate')
    op.drop_column('payments', 'exchange_rate_date')
    op.drop_column('payments', 'base_amount')
    op.drop_column('payments', 'base_currency')
    op.drop_column('payments', 'exchange_rate')
    op.drop_column('payments', 'currency')
    op.drop_column('invoices', 'exchange_rate_date')
    op.drop_column('invoices', 'base_amount')
    op.drop_column('invoices', 'base_currency')
    op.drop_column('invoices', 'exchange_rate')
    op.drop_column('invoices', 'currency')
    op.execute("DROP INDEX IF EXISTS ix_exchange_rates_company_pair_date")
    op.execute("DROP INDEX IF EXISTS ix_exchange_rates_created_by")
    op.execute("DROP INDEX IF EXISTS ix_exchange_rates_company_id")
    op.execute("DROP TABLE IF EXISTS exchange_rates")
    # ### end Alembic commands ###
