"""refactor models to make them production safe

Revision ID: e039a37b664a
Revises: 
Create Date: 2026-04-23 12:44:38.371351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e039a37b664a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_companies_name')
    )
    op.create_index('ix_companies_name', 'companies', ['name'], unique=False)
    op.create_table('approval_workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('entity_type', postgresql.ENUM('PR', 'PO', 'INVOICE', 'PAYMENT', name='entitytypeenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_workflow_name_per_company')
    )
    op.create_index('ix_approval_workflows_company_entity_type', 'approval_workflows', ['company_id', 'entity_type'], unique=False)
    op.create_index('ix_approval_workflows_company_id', 'approval_workflows', ['company_id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_departments_company_name')
    )
    op.create_index(op.f('ix_departments_company_id'), 'departments', ['company_id'], unique=False)
    op.create_index('ix_departments_company_id_name', 'departments', ['company_id', 'name'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_company_role_name')
    )
    op.create_index(op.f('ix_roles_company_id'), 'roles', ['company_id'], unique=False)
    op.create_index('ix_roles_company_id_name', 'roles', ['company_id', 'name'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('contact_person', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_suppliers_company_name')
    )
    op.create_index(op.f('ix_suppliers_company_id'), 'suppliers', ['company_id'], unique=False)
    op.create_index('ix_suppliers_company_id_name', 'suppliers', ['company_id', 'name'], unique=False)
    op.create_index(op.f('ix_suppliers_email'), 'suppliers', ['email'], unique=False)
    op.create_index(op.f('ix_suppliers_phone'), 'suppliers', ['phone'], unique=False)
    op.create_table('supplier_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_id', 'email', name='uq_supplier_users_supplier_email')
    )
    op.create_index(op.f('ix_supplier_users_email'), 'supplier_users', ['email'], unique=False)
    op.create_index(op.f('ix_supplier_users_supplier_id'), 'supplier_users', ['supplier_id'], unique=False)
    op.create_index('ix_supplier_users_supplier_id_email', 'supplier_users', ['supplier_id', 'email'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'email', name='uq_users_company_email')
    )
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_index('ix_users_company_id_department_id', 'users', ['company_id', 'department_id'], unique=False)
    op.create_index('ix_users_company_id_email', 'users', ['company_id', 'email'], unique=False)
    op.create_index('ix_users_company_id_role_id', 'users', ['company_id', 'role_id'], unique=False)
    op.create_index(op.f('ix_users_department_id'), 'users', ['department_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_table('workflow_levels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('level_order', sa.Integer(), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('max_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('condition_expression', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['approval_workflows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'level_order', name='uq_workflow_level_level_order')
    )
    op.create_index('ix_workflow_levels_company_id', 'workflow_levels', ['company_id'], unique=False)
    op.create_index('ix_workflow_levels_department_id', 'workflow_levels', ['department_id'], unique=False)
    op.create_index('ix_workflow_levels_workflow_id', 'workflow_levels', ['workflow_id'], unique=False)
    op.create_index('ix_workflow_levels_workflow_level_order', 'workflow_levels', ['workflow_id', 'level_order'], unique=False)
    op.create_table('approval_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', postgresql.ENUM('PR', 'PO', 'INVOICE', 'PAYMENT', name='entitytypeenum'), nullable=False),
    sa.Column('current_level_id', sa.UUID(), nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='approvalstatusenum'), server_default='PENDING', nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['current_level_id'], ['workflow_levels.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['approval_workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_approval_instances_company_entity', 'approval_instances', ['company_id', 'entity_id'], unique=False)
    op.create_index('idx_approval_instances_company_id', 'approval_instances', ['company_id'], unique=False)
    op.create_index('idx_approval_instances_entity_id', 'approval_instances', ['entity_id'], unique=False)
    op.create_index('idx_approval_instances_workflow_id', 'approval_instances', ['workflow_id'], unique=False)
    op.create_table('purchase_requisitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('pr_number', sa.String(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'CANCELLED', 'CONVERTED_TO_PO', name='prstatusenum'), server_default='DRAFT', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'pr_number', name='uq_pr_company_pr_number')
    )
    op.create_index('ix_pr_company_id_department_id', 'purchase_requisitions', ['company_id', 'department_id'], unique=False)
    op.create_index('ix_pr_company_id_pr_number', 'purchase_requisitions', ['company_id', 'pr_number'], unique=False)
    op.create_index('ix_pr_company_id_requested_by', 'purchase_requisitions', ['company_id', 'requested_by'], unique=False)
    op.create_index('ix_pr_company_id_status', 'purchase_requisitions', ['company_id', 'status'], unique=False)
    op.create_index(op.f('ix_purchase_requisitions_company_id'), 'purchase_requisitions', ['company_id'], unique=False)
    op.create_index(op.f('ix_purchase_requisitions_department_id'), 'purchase_requisitions', ['department_id'], unique=False)
    op.create_index(op.f('ix_purchase_requisitions_requested_by'), 'purchase_requisitions', ['requested_by'], unique=False)
    op.create_index(op.f('ix_purchase_requisitions_status'), 'purchase_requisitions', ['status'], unique=False)
    op.create_table('workflow_level_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('level_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['workflow_levels.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level_id', 'role_id', name='uq_workflow_level_roles')
    )
    op.create_index('ix_workflow_level_roles_company_id', 'workflow_level_roles', ['company_id'], unique=False)
    op.create_index('ix_workflow_level_roles_level_id', 'workflow_level_roles', ['level_id'], unique=False)
    op.create_index('ix_workflow_level_roles_role_id', 'workflow_level_roles', ['role_id'], unique=False)
    op.create_table('approval_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('instance_id', sa.UUID(), nullable=False),
    sa.Column('level_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', postgresql.ENUM('APPROVED', 'REJECTED', name='actiontypeenum'), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['instance_id'], ['approval_instances.id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['workflow_levels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instance_id', 'level_id', 'user_id', name='uq_user_level_action')
    )
    op.create_index('ix_approval_actions_company_id', 'approval_actions', ['company_id'], unique=False)
    op.create_index('ix_approval_actions_instance_id', 'approval_actions', ['instance_id'], unique=False)
    op.create_index('ix_approval_actions_level_id', 'approval_actions', ['level_id'], unique=False)
    op.create_index('ix_approval_actions_user_id', 'approval_actions', ['user_id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('po_number', sa.String(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('submitted_by', sa.UUID(), nullable=True),
    sa.Column('issued_by', sa.UUID(), nullable=True),
    sa.Column('purchase_requisition_id', sa.UUID(), nullable=True),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('status', postgresql.ENUM('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'SENT', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED', name='postatusenum'), server_default='DRAFT', nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(), server_default='KES', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['purchase_requisition_id'], ['purchase_requisitions.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'po_number', name='uq_po_company_po_number')
    )
    op.create_index('ix_po_company_id_po_number', 'purchase_orders', ['company_id', 'po_number'], unique=False)
    op.create_index('ix_po_company_id_status', 'purchase_orders', ['company_id', 'status'], unique=False)
    op.create_index('ix_purchase_orders_company_id', 'purchase_orders', ['company_id'], unique=False)
    op.create_index('ix_purchase_orders_created_by', 'purchase_orders', ['created_by'], unique=False)
    op.create_index('ix_purchase_orders_department_id', 'purchase_orders', ['department_id'], unique=False)
    op.create_index('ix_purchase_orders_issued_by', 'purchase_orders', ['issued_by'], unique=False)
    op.create_index('ix_purchase_orders_purchase_requisition_id', 'purchase_orders', ['purchase_requisition_id'], unique=False)
    op.create_index('ix_purchase_orders_submitted_by', 'purchase_orders', ['submitted_by'], unique=False)
    op.create_index('ix_purchase_orders_supplier_id', 'purchase_orders', ['supplier_id'], unique=False)
    op.create_table('purchase_requisition_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('requisition_id', sa.UUID(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requisition_id'], ['purchase_requisitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pr_item_company_id_requisition_id', 'purchase_requisition_items', ['company_id', 'requisition_id'], unique=False)
    op.create_index('ix_pr_item_item_name', 'purchase_requisition_items', ['item_name'], unique=False)
    op.create_index(op.f('ix_purchase_requisition_items_company_id'), 'purchase_requisition_items', ['company_id'], unique=False)
    op.create_index(op.f('ix_purchase_requisition_items_requisition_id'), 'purchase_requisition_items', ['requisition_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=True),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('submitted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('submitted_by_supplier_user_id', sa.UUID(), nullable=True),
    sa.Column('invoice_number', sa.String(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'SENT', 'PARTIALLY_PAID', 'PAID', 'CANCELLED', name='invoicestatusenum'), server_default='DRAFT', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('\n            (\n                submitted_by_user_id IS NOT NULL\n                AND submitted_by_supplier_user_id IS NULL\n            )\n            OR\n            (\n                submitted_by_user_id IS NULL\n                AND submitted_by_supplier_user_id IS NOT NULL\n            )\n            ', name='ck_invoice_only_one_submitter'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_supplier_user_id'], ['supplier_users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'invoice_number', name='uq_invoices_company_invoice_number')
    )
    op.create_index(op.f('ix_invoices_company_id'), 'invoices', ['company_id'], unique=False)
    op.create_index('ix_invoices_company_po', 'invoices', ['company_id', 'purchase_order_id'], unique=False)
    op.create_index('ix_invoices_company_supplier', 'invoices', ['company_id', 'supplier_id'], unique=False)
    op.create_index(op.f('ix_invoices_purchase_order_id'), 'invoices', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_index(op.f('ix_invoices_submitted_by_supplier_user_id'), 'invoices', ['submitted_by_supplier_user_id'], unique=False)
    op.create_index(op.f('ix_invoices_submitted_by_user_id'), 'invoices', ['submitted_by_user_id'], unique=False)
    op.create_index(op.f('ix_invoices_supplier_id'), 'invoices', ['supplier_id'], unique=False)
    op.create_table('po_email_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('recipient_email', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('status', postgresql.ENUM('SENT', 'FAILED', 'PENDING', name='emailstatusenum'), server_default='SENT', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_by', sa.UUID(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['sent_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_po_email_logs_company_id', 'po_email_logs', ['company_id'], unique=False)
    op.create_index('ix_po_email_logs_purchase_order_id', 'po_email_logs', ['purchase_order_id'], unique=False)
    op.create_index('ix_po_email_logs_sent_by', 'po_email_logs', ['sent_by'], unique=False)
    op.create_index('ix_po_email_logs_status', 'po_email_logs', ['status'], unique=False)
    op.create_index('ix_po_email_logs_supplier_id', 'po_email_logs', ['supplier_id'], unique=False)
    op.create_table('purchase_order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_purchase_order_items_company_id', 'purchase_order_items', ['company_id'], unique=False)
    op.create_index('ix_purchase_order_items_item_name', 'purchase_order_items', ['item_name'], unique=False)
    op.create_index('ix_purchase_order_items_purchase_order_id', 'purchase_order_items', ['purchase_order_id'], unique=False)
    op.create_table('invoice_line_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_item_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('invoiced_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_item_id'], ['purchase_order_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_line_items_company_id'), 'invoice_line_items', ['company_id'], unique=False)
    op.create_index('ix_invoice_line_items_company_invoice', 'invoice_line_items', ['company_id', 'invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_line_items_invoice_id'), 'invoice_line_items', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_line_items_purchase_order_item_id'), 'invoice_line_items', ['purchase_order_item_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', postgresql.ENUM('BANK_TRANSFER', 'MPESA', 'CASH', name='paymentmethodenum'), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', 'REJECTED', name='paymentstatusenum'), server_default='COMPLETED', nullable=False),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_company_id'), 'payments', ['company_id'], unique=False)
    op.create_index('ix_payments_company_invoice', 'payments', ['company_id', 'invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_created_by'), 'payments', ['created_by'], unique=False)
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_method'), 'payments', ['payment_method'], unique=False)
    op.create_index(op.f('ix_payments_reference'), 'payments', ['reference'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_reference'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_method'), table_name='payments')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_by'), table_name='payments')
    op.drop_index('ix_payments_company_invoice', table_name='payments')
    op.drop_index(op.f('ix_payments_company_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_invoice_line_items_purchase_order_item_id'), table_name='invoice_line_items')
    op.drop_index(op.f('ix_invoice_line_items_invoice_id'), table_name='invoice_line_items')
    op.drop_index('ix_invoice_line_items_company_invoice', table_name='invoice_line_items')
    op.drop_index(op.f('ix_invoice_line_items_company_id'), table_name='invoice_line_items')
    op.drop_table('invoice_line_items')
    op.drop_index('ix_purchase_order_items_purchase_order_id', table_name='purchase_order_items')
    op.drop_index('ix_purchase_order_items_item_name', table_name='purchase_order_items')
    op.drop_index('ix_purchase_order_items_company_id', table_name='purchase_order_items')
    op.drop_table('purchase_order_items')
    op.drop_index('ix_po_email_logs_supplier_id', table_name='po_email_logs')
    op.drop_index('ix_po_email_logs_status', table_name='po_email_logs')
    op.drop_index('ix_po_email_logs_sent_by', table_name='po_email_logs')
    op.drop_index('ix_po_email_logs_purchase_order_id', table_name='po_email_logs')
    op.drop_index('ix_po_email_logs_company_id', table_name='po_email_logs')
    op.drop_table('po_email_logs')
    op.drop_index(op.f('ix_invoices_supplier_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_submitted_by_user_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_submitted_by_supplier_user_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_purchase_order_id'), table_name='invoices')
    op.drop_index('ix_invoices_company_supplier', table_name='invoices')
    op.drop_index('ix_invoices_company_po', table_name='invoices')
    op.drop_index(op.f('ix_invoices_company_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_purchase_requisition_items_requisition_id'), table_name='purchase_requisition_items')
    op.drop_index(op.f('ix_purchase_requisition_items_company_id'), table_name='purchase_requisition_items')
    op.drop_index('ix_pr_item_item_name', table_name='purchase_requisition_items')
    op.drop_index('ix_pr_item_company_id_requisition_id', table_name='purchase_requisition_items')
    op.drop_table('purchase_requisition_items')
    op.drop_index('ix_purchase_orders_supplier_id', table_name='purchase_orders')
    op.drop_index('ix_purchase_orders_submitted_by', table_name='purchase_orders')
    op.drop_index('ix_purchase_orders_purchase_requisition_id', table_name='purchase_orders')
    op.drop_index('ix_purchase_orders_issued_by', table_name='purchase_orders')
    op.drop_index('ix_purchase_orders_department_id', table_name='purchase_orders')
    op.drop_index('ix_purchase_orders_created_by', table_name='purchase_orders')
    op.drop_index('ix_purchase_orders_company_id', table_name='purchase_orders')
    op.drop_index('ix_po_company_id_status', table_name='purchase_orders')
    op.drop_index('ix_po_company_id_po_number', table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index('ix_approval_actions_user_id', table_name='approval_actions')
    op.drop_index('ix_approval_actions_level_id', table_name='approval_actions')
    op.drop_index('ix_approval_actions_instance_id', table_name='approval_actions')
    op.drop_index('ix_approval_actions_company_id', table_name='approval_actions')
    op.drop_table('approval_actions')
    op.drop_index('ix_workflow_level_roles_role_id', table_name='workflow_level_roles')
    op.drop_index('ix_workflow_level_roles_level_id', table_name='workflow_level_roles')
    op.drop_index('ix_workflow_level_roles_company_id', table_name='workflow_level_roles')
    op.drop_table('workflow_level_roles')
    op.drop_index(op.f('ix_purchase_requisitions_status'), table_name='purchase_requisitions')
    op.drop_index(op.f('ix_purchase_requisitions_requested_by'), table_name='purchase_requisitions')
    op.drop_index(op.f('ix_purchase_requisitions_department_id'), table_name='purchase_requisitions')
    op.drop_index(op.f('ix_purchase_requisitions_company_id'), table_name='purchase_requisitions')
    op.drop_index('ix_pr_company_id_status', table_name='purchase_requisitions')
    op.drop_index('ix_pr_company_id_requested_by', table_name='purchase_requisitions')
    op.drop_index('ix_pr_company_id_pr_number', table_name='purchase_requisitions')
    op.drop_index('ix_pr_company_id_department_id', table_name='purchase_requisitions')
    op.drop_table('purchase_requisitions')
    op.drop_index('idx_approval_instances_workflow_id', table_name='approval_instances')
    op.drop_index('idx_approval_instances_entity_id', table_name='approval_instances')
    op.drop_index('idx_approval_instances_company_id', table_name='approval_instances')
    op.drop_index('idx_approval_instances_company_entity', table_name='approval_instances')
    op.drop_table('approval_instances')
    op.drop_index('ix_workflow_levels_workflow_level_order', table_name='workflow_levels')
    op.drop_index('ix_workflow_levels_workflow_id', table_name='workflow_levels')
    op.drop_index('ix_workflow_levels_department_id', table_name='workflow_levels')
    op.drop_index('ix_workflow_levels_company_id', table_name='workflow_levels')
    op.drop_table('workflow_levels')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_department_id'), table_name='users')
    op.drop_index('ix_users_company_id_role_id', table_name='users')
    op.drop_index('ix_users_company_id_email', table_name='users')
    op.drop_index('ix_users_company_id_department_id', table_name='users')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_supplier_users_supplier_id_email', table_name='supplier_users')
    op.drop_index(op.f('ix_supplier_users_supplier_id'), table_name='supplier_users')
    op.drop_index(op.f('ix_supplier_users_email'), table_name='supplier_users')
    op.drop_table('supplier_users')
    op.drop_index(op.f('ix_suppliers_phone'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_email'), table_name='suppliers')
    op.drop_index('ix_suppliers_company_id_name', table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_company_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index('ix_roles_company_id_name', table_name='roles')
    op.drop_index(op.f('ix_roles_company_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index('ix_departments_company_id_name', table_name='departments')
    op.drop_index(op.f('ix_departments_company_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index('ix_approval_workflows_company_id', table_name='approval_workflows')
    op.drop_index('ix_approval_workflows_company_entity_type', table_name='approval_workflows')
    op.drop_table('approval_workflows')
    op.drop_index('ix_companies_name', table_name='companies')
    op.drop_table('companies')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
